name: HACS validate

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    validate:
        name: HACS validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: HACS validate
              uses: hacs/action@main
              with:
                  category: 'plugin'
